#############################################################################
# Makefile for building: jy10_01
# Generated by qmake (2.01a) (Qt 4.8.1) on: ?? 8? 15 15:16:57 2016
# Project:  jy10_01.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile jy10_01.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -Ihwlib -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = camera.cpp \
		camera_thread.cpp \
		canread.cpp \
		findlook.cpp \
		main.cpp \
		signalcan.cpp \
		timesetup.cpp \
		timesetuptrue.cpp \
		videodevice.cpp \
		widget.cpp \
		work.cpp moc_camera.cpp \
		moc_camera_thread.cpp \
		moc_findlook.cpp \
		moc_signalcan.cpp \
		moc_timesetup.cpp \
		moc_timesetuptrue.cpp \
		moc_videodevice.cpp \
		moc_widget.cpp \
		moc_work.cpp \
		qrc_imagejy.cpp
OBJECTS       = camera.o \
		camera_thread.o \
		canread.o \
		findlook.o \
		main.o \
		signalcan.o \
		timesetup.o \
		timesetuptrue.o \
		videodevice.o \
		widget.o \
		work.o \
		moc_camera.o \
		moc_camera_thread.o \
		moc_findlook.o \
		moc_signalcan.o \
		moc_timesetup.o \
		moc_timesetuptrue.o \
		moc_videodevice.o \
		moc_widget.o \
		moc_work.o \
		qrc_imagejy.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		jy10_01.pro
QMAKE_TARGET  = jy10_01
DESTDIR       = 
TARGET        = jy10_01

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_findlook.h ui_timesetup.h ui_timesetuptrue.h ui_widget.h ui_work.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: jy10_01.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile jy10_01.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile jy10_01.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/jy10_011.0.0 || $(MKDIR) .tmp/jy10_011.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/jy10_011.0.0/ && $(COPY_FILE) --parents camera.h camera_thread.h canread.h common.h findlook.h mylib.h signalcan.h timesetup.h timesetuptrue.h videodevice.h widget.h work.h hwlib/devlib.h .tmp/jy10_011.0.0/ && $(COPY_FILE) --parents imagejy.qrc .tmp/jy10_011.0.0/ && $(COPY_FILE) --parents camera.cpp camera_thread.cpp canread.cpp findlook.cpp main.cpp signalcan.cpp timesetup.cpp timesetuptrue.cpp videodevice.cpp widget.cpp work.cpp .tmp/jy10_011.0.0/ && $(COPY_FILE) --parents findlook.ui timesetup.ui timesetuptrue.ui widget.ui work.ui .tmp/jy10_011.0.0/ && (cd `dirname .tmp/jy10_011.0.0` && $(TAR) jy10_011.0.0.tar jy10_011.0.0 && $(COMPRESS) jy10_011.0.0.tar) && $(MOVE) `dirname .tmp/jy10_011.0.0`/jy10_011.0.0.tar.gz . && $(DEL_FILE) -r .tmp/jy10_011.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_camera.cpp moc_camera_thread.cpp moc_findlook.cpp moc_signalcan.cpp moc_timesetup.cpp moc_timesetuptrue.cpp moc_videodevice.cpp moc_widget.cpp moc_work.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_camera.cpp moc_camera_thread.cpp moc_findlook.cpp moc_signalcan.cpp moc_timesetup.cpp moc_timesetuptrue.cpp moc_videodevice.cpp moc_widget.cpp moc_work.cpp
moc_camera.cpp: videodevice.h \
		camera.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) camera.h -o moc_camera.cpp

moc_camera_thread.cpp: camera.h \
		videodevice.h \
		camera_thread.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) camera_thread.h -o moc_camera_thread.cpp

moc_findlook.cpp: findlook.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) findlook.h -o moc_findlook.cpp

moc_signalcan.cpp: canread.h \
		signalcan.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) signalcan.h -o moc_signalcan.cpp

moc_timesetup.cpp: timesetuptrue.h \
		timesetup.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) timesetup.h -o moc_timesetup.cpp

moc_timesetuptrue.cpp: timesetuptrue.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) timesetuptrue.h -o moc_timesetuptrue.cpp

moc_videodevice.cpp: videodevice.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) videodevice.h -o moc_videodevice.cpp

moc_widget.cpp: work.h \
		findlook.h \
		timesetup.h \
		timesetuptrue.h \
		camera_thread.h \
		camera.h \
		videodevice.h \
		signalcan.h \
		canread.h \
		widget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

moc_work.cpp: findlook.h \
		timesetup.h \
		timesetuptrue.h \
		camera_thread.h \
		camera.h \
		videodevice.h \
		work.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) work.h -o moc_work.cpp

compiler_rcc_make_all: qrc_imagejy.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_imagejy.cpp
qrc_imagejy.cpp: imagejy.qrc \
		imagejy/find.png \
		imagejy/back.png \
		imagejy/timeseticon.png \
		imagejy/yjsd.png \
		imagejy/setup.png \
		imagejy/jiaozhun.png \
		imagejy/03-1.png \
		imagejy/qihuan.png \
		imagejy/laba.png
	/usr/bin/rcc -name imagejy imagejy.qrc -o qrc_imagejy.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_findlook.h ui_timesetup.h ui_timesetuptrue.h ui_widget.h ui_work.h
compiler_uic_clean:
	-$(DEL_FILE) ui_findlook.h ui_timesetup.h ui_timesetuptrue.h ui_widget.h ui_work.h
ui_findlook.h: findlook.ui
	/usr/bin/uic-qt4 findlook.ui -o ui_findlook.h

ui_timesetup.h: timesetup.ui
	/usr/bin/uic-qt4 timesetup.ui -o ui_timesetup.h

ui_timesetuptrue.h: timesetuptrue.ui
	/usr/bin/uic-qt4 timesetuptrue.ui -o ui_timesetuptrue.h

ui_widget.h: widget.ui
	/usr/bin/uic-qt4 widget.ui -o ui_widget.h

ui_work.h: work.ui
	/usr/bin/uic-qt4 work.ui -o ui_work.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

camera.o: camera.cpp camera.h \
		videodevice.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cpp

camera_thread.o: camera_thread.cpp camera_thread.h \
		camera.h \
		videodevice.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera_thread.o camera_thread.cpp

canread.o: canread.cpp canread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o canread.o canread.cpp

findlook.o: findlook.cpp findlook.h \
		ui_findlook.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o findlook.o findlook.cpp

main.o: main.cpp widget.h \
		work.h \
		findlook.h \
		timesetup.h \
		timesetuptrue.h \
		camera_thread.h \
		camera.h \
		videodevice.h \
		signalcan.h \
		canread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

signalcan.o: signalcan.cpp signalcan.h \
		canread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o signalcan.o signalcan.cpp

timesetup.o: timesetup.cpp timesetup.h \
		timesetuptrue.h \
		ui_timesetup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timesetup.o timesetup.cpp

timesetuptrue.o: timesetuptrue.cpp timesetuptrue.h \
		ui_timesetuptrue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timesetuptrue.o timesetuptrue.cpp

videodevice.o: videodevice.cpp videodevice.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o videodevice.o videodevice.cpp

widget.o: widget.cpp widget.h \
		work.h \
		findlook.h \
		timesetup.h \
		timesetuptrue.h \
		camera_thread.h \
		camera.h \
		videodevice.h \
		signalcan.h \
		canread.h \
		ui_widget.h \
		hwlib/devlib.h \
		mylib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

work.o: work.cpp work.h \
		findlook.h \
		timesetup.h \
		timesetuptrue.h \
		camera_thread.h \
		camera.h \
		videodevice.h \
		ui_work.h \
		hwlib/devlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o work.o work.cpp

moc_camera.o: moc_camera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camera.o moc_camera.cpp

moc_camera_thread.o: moc_camera_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camera_thread.o moc_camera_thread.cpp

moc_findlook.o: moc_findlook.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_findlook.o moc_findlook.cpp

moc_signalcan.o: moc_signalcan.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_signalcan.o moc_signalcan.cpp

moc_timesetup.o: moc_timesetup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timesetup.o moc_timesetup.cpp

moc_timesetuptrue.o: moc_timesetuptrue.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timesetuptrue.o moc_timesetuptrue.cpp

moc_videodevice.o: moc_videodevice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_videodevice.o moc_videodevice.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

moc_work.o: moc_work.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_work.o moc_work.cpp

qrc_imagejy.o: qrc_imagejy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_imagejy.o qrc_imagejy.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

